Repository async-rs/async-std, pull requests merged in 2019-09, with the labels that each got.

#189 links the timeout docs to each other
  src/future/timeout.rs
  src/io/timeout.rs
Labels: documentation

#202 Document feature flags in readme
  README.md
Labels: documentation

#208 add stream::join
  Cargo.toml
  src/stream/mod.rs
Labels: enhancement

#216 fix unstable display for pin docs
  src/lib.rs
Labels: bug, documentation

#139 Rename server functions to follow *_loop convention
  docs/src/tutorial/accept_loop.md
  docs/src/tutorial/all_together.md
  docs/src/tutorial/clean_shutdown.md
  docs/src/tutorial/connecting_readers_and_writers.md
  docs/src/tutorial/handling_disconnection.md
  docs/src/tutorial/receiving_messages.md
  docs/src/tutorial/sending_messages.md
Labels: documentation

#92 draft Buf writer
  src/io/buf_writer.rs
  src/io/mod.rs
Labels: enhancement

#256 update changelog
  CHANGELOG.md
Labels: documentation

#260 update Barrier example to match std::sync::Barrier 1:1
  src/sync/barrier.rs
Labels: documentation

#253 Add github actions workflows
  .github/workflows/ci.yml
  .github/workflows/clippy.yml
Labels: enhancement
