Repository async-rs/async-std, pull requests merged in 2019-11, with the labels that each got.

#181 Spawn several threads when we fail to enqueue work in the blocki…
  src/task/spawn_blocking.rs
Labels: enhancement

#334 Locking for stdin
  src/io/mod.rs
  src/io/stderr.rs
  src/io/stdin.rs
  src/io/stdout.rs
Labels: enhancement

#405 Replace select!/try_select! with Future::{race,try_race}
  src/future/future/mod.rs
  src/future/future/race.rs
  src/future/future/try_race.rs
  src/future/mod.rs
  src/utils.rs
Labels: api design, enhancement

#388 Implement stream::cycle(..)
  src/stream/stream/cycle.rs
  src/stream/stream/mod.rs
Labels: enhancement

#467 document path submodule
  src/path/mod.rs
Labels: documentation

#238 re-export async-attributes
  Cargo.toml
  src/lib.rs
Labels: enhancement

#513 fix changelog
  CHANGELOG.md
Labels: documentation

#356 Implemented StreamExt::throttle
  examples/throttle.rs
  src/stream/stream/mod.rs
  src/stream/stream/throttle.rs
Labels: enhancement

#368 add stream::count
  src/stream/stream/count.rs
  src/stream/stream/mod.rs
Labels: enhancement

#535 backlink channel types
  src/sync/channel.rs
Labels: documentation

#363 Async successors
  src/stream/mod.rs
  src/stream/successors.rs
Labels: enhancement

#551 verbose errors feature
  src/fs/file.rs
  src/io/mod.rs
  src/io/utils.rs
  src/utils.rs
  tests/verbose_errors.rs
Labels: enhancement

#526 refactor io dir to be same with std and export IntoInnerError
  src/io/buf_reader.rs
  src/io/buf_writer.rs
  src/io/mod.rs
Labels: enhancement

#552 add os::windows::symlink_{dir,file}
  src/fs/mod.rs
  src/os/windows/fs.rs
  src/os/windows/mod.rs
Labels: enhancement

#567 mark windows fs APIs as "unstable"
  src/os/windows/mod.rs
Labels: bug

#523 polish lib.rs examples
  .github/workflows/ci.yml
  README.md
  src/lib.rs
  src/task/block_on.rs
Labels: documentation

#584 fix Stream::throttle hot loop
  src/stream/stream/mod.rs
  src/stream/stream/throttle.rs
Labels: bug

#309 Stream::delay
  src/stream/stream/delay.rs
  src/stream/stream/mod.rs
Labels: enhancement
