Repository async-rs/async-std, pull requests merged in 2019-10, with the labels that each got.

#282 init path submodule as unstable
  src/lib.rs
  src/path/mod.rs
Labels: enhancement

#287 Optimizing allocations using Stream::size_hint
  src/collections/binary_heap/extend.rs
  src/collections/hash_map/extend.rs
  src/collections/hash_set/extend.rs
  src/collections/linked_list/extend.rs
  src/collections/vec_deque/extend.rs
  src/string/extend.rs
  src/vec/extend.rs
Labels: enhancement

#251 add an unstable `task::blocking` function
  src/fs/read_dir.rs
  src/io/stderr.rs
  src/io/stdin.rs
  src/io/stdout.rs
  src/net/addr.rs
  src/task/blocking.rs
  src/task/mod.rs
Labels: enhancement

#294 add task::blocking docs
  src/task/block_on.rs
  src/task/mod.rs
Labels: documentation

#283 Add GitHub Actions to the merge requirement of bors
  .github/workflows/ci.yml
  .github/workflows/clippy.yml
  bors.toml
Labels: enhancement

#311 Add Write::write_fmt
  src/io/write/mod.rs
  src/io/write/write_fmt.rs
  src/lib.rs
Labels: enhancement

#321 rename stream::join to Stream::merge
  src/stream/mod.rs
  src/stream/stream/merge.rs
  src/stream/stream/mod.rs
Labels: enhancement

#300 Add task::yield_now as "unstable"
  src/task/mod.rs
  src/task/yield_now.rs
Labels: enhancement

#326 add stream::FusedStream as "unstable"
  src/stream/fused_stream.rs
  src/stream/mod.rs
Labels: enhancement

#322 make all print macros unstable
  src/lib.rs
  src/macros.rs
Labels: bug

#325 stabilize task::ready!
  src/task/mod.rs
Labels: enhancement

#324 stabilize future::{join,try_join}
  src/future/mod.rs
Labels: enhancement

#312 Add BufRead::split
  src/io/buf_read/mod.rs
  src/io/buf_read/split.rs
Labels: enhancement

#310 Add process submodule as unstable
  src/lib.rs
  src/process/mod.rs
Labels: enhancement

#298 add stream::interval
  Cargo.toml
  src/io/timeout.rs
  src/stream/interval.rs
  src/stream/mod.rs
  src/task/sleep.rs
Labels: enhancement

#277 Adds a from_fn stream implementation
  src/stream/from_fn.rs
  src/stream/mod.rs
Labels: enhancement

#259 add IntoFuture
  src/future/into_future.rs
  src/future/mod.rs
Labels: enhancement

#299 Blocking updates
  src/fs/canonicalize.rs
  src/fs/copy.rs
  src/fs/create_dir.rs
  src/fs/create_dir_all.rs
  src/fs/dir_builder.rs
  src/fs/dir_entry.rs
  src/fs/file.rs
  src/fs/hard_link.rs
  src/fs/metadata.rs
  src/fs/open_options.rs
  src/fs/read.rs
  src/fs/read_dir.rs
  src/fs/read_link.rs
  src/fs/read_to_string.rs
  src/fs/remove_dir.rs
  src/fs/remove_dir_all.rs
  src/fs/remove_file.rs
  src/fs/rename.rs
  src/fs/set_permissions.rs
  src/fs/symlink_metadata.rs
  src/fs/write.rs
  src/io/stderr.rs
  src/io/stdin.rs
  src/io/stdout.rs
  src/net/addr.rs
  src/net/tcp/stream.rs
  src/os/unix/fs.rs
  src/os/unix/net/datagram.rs
  src/os/unix/net/listener.rs
  src/os/unix/net/stream.rs
  src/task/block_on.rs
  src/task/blocking.rs
  src/task/mod.rs
Labels: enhancement

#308 init FutureExt
  src/fs/dir_builder.rs
  src/fs/open_options.rs
  src/future/future.rs
  src/future/mod.rs
  src/io/buf_read/mod.rs
  src/io/read/mod.rs
  src/io/seek.rs
  src/io/write/mod.rs
  src/prelude.rs
  src/stream/stream/mod.rs
  src/task/blocking.rs
  src/task/task.rs
  src/task/task_local.rs
  src/utils.rs
Labels: enhancement

#343 add stream::{Sum,Product}
  src/stream/mod.rs
  src/stream/product.rs
  src/stream/sum.rs
  src/task/blocking.rs
Labels: enhancement

#304 [Draft PR] Adds Stream::gt
  src/stream/stream/gt.rs
  src/stream/stream/mod.rs
Labels: enhancement

#285 Adds Stream:ge
  src/stream/stream/ge.rs
  src/stream/stream/mod.rs
Labels: enhancement

#273 Adds Stream::cmp
  src/stream/stream/cmp.rs
  src/stream/stream/mod.rs
Labels: enhancement

#345 Io docs
  src/io/mod.rs
Labels: documentation

#346 task docs
  src/stream/mod.rs
  src/task/mod.rs
Labels: documentation

#279 Adds stream::repeat_with
  src/stream/mod.rs
  src/stream/repeat_with.rs
Labels: enhancement

#394 backreference links for structs
  src/io/empty.rs
  src/io/repeat.rs
  src/io/sink.rs
  src/io/stderr.rs
  src/io/stdin.rs
  src/io/stdout.rs
  src/stream/empty.rs
  src/stream/from_fn.rs
  src/stream/interval.rs
  src/stream/once.rs
  src/stream/repeat.rs
  src/stream/repeat_with.rs
  src/stream/stream/chain.rs
  src/stream/stream/filter.rs
  src/stream/stream/fuse.rs
  src/stream/stream/inspect.rs
  src/stream/stream/merge.rs
  src/stream/stream/scan.rs
  src/stream/stream/skip.rs
  src/stream/stream/skip_while.rs
  src/stream/stream/step_by.rs
  src/stream/stream/take.rs
  src/stream/stream/take_while.rs
  src/stream/stream/zip.rs
Labels: documentation

#349 Add future::delay
  src/future/future.rs
  src/future/future/delay.rs
Labels: enhancement

#367 Add Stream::flatten and Stream::flat_map
  src/stream/stream/flat_map.rs
  src/stream/stream/flatten.rs
  src/stream/stream/mod.rs
Labels: enhancement

#396 standardize net docs
  src/net/mod.rs
Labels: documentation

#402 update Stream::fuse docs
  src/stream/stream/fuse.rs
  src/stream/stream/mod.rs
Labels: documentation

#395 add stream mod docs
  src/stream/mod.rs
Labels: documentation

#397 add mod level docs for sync
  src/sync/mod.rs
Labels: documentation

#385 add stream::min_by_key method
  src/stream/stream/min_by_key.rs
  src/stream/stream/mod.rs
Labels: enhancement

#384 add stream::max_by method
  src/stream/stream/max_by.rs
  src/stream/stream/mod.rs
Labels: enhancement
